"""remove created_at and updated_at columns from tags table

Revision ID: 20c7eabce4fb
Revises: 9de9f857831f
Create Date: 2026-08-25 00:33:42.913226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c7eabce4fb'
down_revision: Union[str, Sequence[str], None] = '9de9f857831f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_tags', 'updated_at')
    op.drop_column('t_tags', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_tags', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('t_tags', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
