"""add m_users table

Revision ID: a5d22f0c6fdd
Revises: 20c7eabce4fb
Create Date: 2026-08-31 13:48:03.832241

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "a5d22f0c6fdd"
down_revision: Union[str, Sequence[str], None] = "20c7eabce4fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "m_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "role",
            sa.Enum("superadmin", "admin_recipe", "admin_tag", name="userroleenum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_m_users_username"), "m_users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_m_users_username"), table_name="m_users")
    op.drop_table("m_users")
    # ### end Alembic commands ###
